id: I14CCA0A6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:04:04+00:00'
last_modified: '2022-06-08T12:40:06.128773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19249
  title: སྐྱེ་འཕེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    5D04:
      image_group_id: I8LS19251
      title: ''
      total_pages: 62
      order: 1
      base_file: 5D04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
