id: P010312
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19249
  title: སྐྱེ་འཕེལ།
  author: ''
  volumes:
    2f70a7b54f684e289c1660d49300058d:
      image_group_id: I8LS19251
      title: ''
      volume_number: 1
      total_pages: 62
